version: "3.8"
services: 
    postgis:
        container_name: postgis
        image: postgis/postgis:12-3.0
        environment: 
            - POSTGRES_USER=postgis
            - POSTGRES_PASSWORD=postgis
            - POSTGRES_DB=postgis
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports: 
            # PostgreSQL connectivity port
            - 5432:5432
volumes:
    pgdata:
